name: Simple WAR Builder

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
      - run: mvn -f back/pom.xml clean package -DskipTests
      - uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: back/target/*.war
